"""
Type signatures for Menai builtin operations.

Each entry maps a builtin name (as it appears in BUILTIN_OPCODE_MAP) to a
tuple of (arg_types, result_type), where types are represented as strings
matching the Menai type names: 'integer', 'float', 'complex', 'string',
'boolean', 'symbol', 'list', 'dict', 'set', 'function', 'bytes', 'none',
'struct'.

The special value None means "unknown type" — used for builtins whose result
type depends on operand types in ways this table does not capture, or for
arguments that accept any type.

This table is used by the CFG type propagation pass to determine the result
type of each builtin call and to verify that operand types are statically
known when deciding whether a runtime type check can be omitted.
"""


# Type alias for a single Menai type name or None (unknown).
MenaiTypeTag = str | None

# Type signature: (list of arg types, result type).
TypeSignature = tuple[list[MenaiTypeTag], MenaiTypeTag]


BUILTIN_TYPE_SIGNATURES: dict[str, TypeSignature] = {
    # None operations
    'none?': (['any'], 'boolean'),

    # Function operations
    'function?': (['any'], 'boolean'),
    'function=?': (['function', 'function'], 'boolean'),
    'function!=?': (['function', 'function'], 'boolean'),
    'function-min-arity': (['function'], 'integer'),
    'function-variadic?': (['function'], 'boolean'),
    'function-accepts?': (['function', 'integer'], 'boolean'),

    # Symbol operations
    'symbol?': (['any'], 'boolean'),
    'symbol=?': (['symbol', 'symbol'], 'boolean'),
    'symbol!=?': (['symbol', 'symbol'], 'boolean'),
    'symbol->string': (['symbol'], 'string'),

    # Boolean operations
    'boolean?': (['any'], 'boolean'),
    'boolean=?': (['boolean', 'boolean'], 'boolean'),
    'boolean!=?': (['boolean', 'boolean'], 'boolean'),
    'boolean-not': (['boolean'], 'boolean'),

    # Integer operations
    'integer?': (['any'], 'boolean'),
    'integer=?': (['integer', 'integer'], 'boolean'),
    'integer!=?': (['integer', 'integer'], 'boolean'),
    'integer<?': (['integer', 'integer'], 'boolean'),
    'integer>?': (['integer', 'integer'], 'boolean'),
    'integer<=?': (['integer', 'integer'], 'boolean'),
    'integer>=?': (['integer', 'integer'], 'boolean'),
    'integer-abs': (['integer'], 'integer'),
    'integer+': (['integer', 'integer'], 'integer'),
    'integer-': (['integer', 'integer'], 'integer'),
    'integer*': (['integer', 'integer'], 'integer'),
    'integer/': (['integer', 'integer'], 'integer'),
    'integer%': (['integer', 'integer'], 'integer'),
    'integer-neg': (['integer'], 'integer'),
    'integer-expn': (['integer', 'integer'], 'integer'),
    'integer-bit-not': (['integer'], 'integer'),
    'integer-bit-shift-left': (['integer', 'integer'], 'integer'),
    'integer-bit-shift-right': (['integer', 'integer'], 'integer'),
    'integer-bit-or': (['integer', 'integer'], 'integer'),
    'integer-bit-and': (['integer', 'integer'], 'integer'),
    'integer-bit-xor': (['integer', 'integer'], 'integer'),
    'integer-min': (['integer', 'integer'], 'integer'),
    'integer-max': (['integer', 'integer'], 'integer'),
    'integer->float': (['integer'], 'float'),
    'integer->complex': (['integer', 'integer'], 'complex'),
    'integer->string': (['integer', 'integer'], 'string'),
    'integer-codepoint->string': (['integer'], 'string'),

    # Float operations
    'float?': (['any'], 'boolean'),
    'float=?': (['float', 'float'], 'boolean'),
    'float!=?': (['float', 'float'], 'boolean'),
    'float<?': (['float', 'float'], 'boolean'),
    'float>?': (['float', 'float'], 'boolean'),
    'float<=?': (['float', 'float'], 'boolean'),
    'float>=?': (['float', 'float'], 'boolean'),
    'float-neg': (['float'], 'float'),
    'float+': (['float', 'float'], 'float'),
    'float-': (['float', 'float'], 'float'),
    'float*': (['float', 'float'], 'float'),
    'float/': (['float', 'float'], 'float'),
    'float//': (['float', 'float'], 'float'),
    'float%': (['float', 'float'], 'float'),
    'float-exp': (['float'], 'float'),
    'float-expn': (['float', 'float'], 'float'),
    'float-log': (['float'], 'float'),
    'float-log10': (['float'], 'float'),
    'float-log2': (['float'], 'float'),
    'float-logn': (['float', 'float'], 'float'),
    'float-sin': (['float'], 'float'),
    'float-cos': (['float'], 'float'),
    'float-tan': (['float'], 'float'),
    'float-sqrt': (['float'], 'float'),
    'float-abs': (['float'], 'float'),
    'float->integer': (['float'], 'integer'),
    'float->complex': (['float', 'float'], 'complex'),
    'float->string': (['float'], 'string'),
    'float-floor': (['float'], 'integer'),
    'float-ceil': (['float'], 'integer'),
    'float-round': (['float'], 'integer'),
    'float-min': (['float', 'float'], 'float'),
    'float-max': (['float', 'float'], 'float'),

    # Complex operations
    'complex?': (['any'], 'boolean'),
    'complex=?': (['complex', 'complex'], 'boolean'),
    'complex!=?': (['complex', 'complex'], 'boolean'),
    'complex-real': (['complex'], 'float'),
    'complex-imag': (['complex'], 'float'),
    'complex-abs': (['complex'], 'float'),
    'complex+': (['complex', 'complex'], 'complex'),
    'complex-': (['complex', 'complex'], 'complex'),
    'complex*': (['complex', 'complex'], 'complex'),
    'complex/': (['complex', 'complex'], 'complex'),
    'complex-neg': (['complex'], 'complex'),
    'complex-exp': (['complex'], 'complex'),
    'complex-expn': (['complex', 'complex'], 'complex'),
    'complex-log': (['complex'], 'complex'),
    'complex-log10': (['complex'], 'complex'),
    'complex-logn': (['complex', 'complex'], 'complex'),
    'complex-sin': (['complex'], 'complex'),
    'complex-cos': (['complex'], 'complex'),
    'complex-tan': (['complex'], 'complex'),
    'complex-sqrt': (['complex'], 'complex'),
    'complex->string': (['complex'], 'string'),

    # String operations
    'string?': (['any'], 'boolean'),
    'string=?': (['string', 'string'], 'boolean'),
    'string!=?': (['string', 'string'], 'boolean'),
    'string<?': (['string', 'string'], 'boolean'),
    'string>?': (['string', 'string'], 'boolean'),
    'string<=?': (['string', 'string'], 'boolean'),
    'string>=?': (['string', 'string'], 'boolean'),
    'string-length': (['string'], 'integer'),
    'string-upcase': (['string'], 'string'),
    'string-downcase': (['string'], 'string'),
    'string-trim': (['string'], 'string'),
    'string-trim-left': (['string'], 'string'),
    'string-trim-right': (['string'], 'string'),
    'string->integer': (['string', 'integer'], 'integer'),
    'string->number': (['string'], None),
    'string->list': (['string', 'string'], 'list'),
    'string-ref': (['string', 'integer'], 'string'),
    'string-index': (['string', 'string'], 'integer'),
    'string-prefix?': (['string', 'string'], 'boolean'),
    'string-suffix?': (['string', 'string'], 'boolean'),
    'string->integer-codepoint': (['string'], 'integer'),
    'string-concat': (['string', 'string'], 'string'),
    'string-slice': (['string', 'integer', 'integer'], 'string'),
    'string-replace': (['string', 'string', 'string'], 'string'),

    # List operations
    'list?': (['any'], 'boolean'),
    'list=?': (['list', 'list'], 'boolean'),
    'list!=?': (['list', 'list'], 'boolean'),
    'list-prepend': (['list', 'any'], 'list'),
    'list-append': (['list', 'any'], 'list'),
    'list-reverse': (['list'], 'list'),
    'list-first': (['list'], None),
    'list-rest': (['list'], 'list'),
    'list-last': (['list'], None),
    'list-length': (['list'], 'integer'),
    'list-ref': (['list', 'integer'], None),
    'list-null?': (['list'], 'boolean'),
    'list-member?': (['list', 'any'], 'boolean'),
    'list-index': (['list', 'any'], 'integer'),
    'list-slice': (['list', 'integer', 'integer'], 'list'),
    'list-remove': (['list', 'any'], 'list'),
    'list-concat': (['list', 'list'], 'list'),
    'list->string': (['list', 'string'], 'string'),
    'list->set': (['list'], 'set'),
    'list->bytes': (['list'], 'bytes'),

    # Dict operations
    'dict?': (['any'], 'boolean'),
    'dict=?': (['dict', 'dict'], 'boolean'),
    'dict!=?': (['dict', 'dict'], 'boolean'),
    'dict-keys': (['dict'], 'list'),
    'dict-values': (['dict'], 'list'),
    'dict-length': (['dict'], 'integer'),
    'dict-has?': (['dict', 'any'], 'boolean'),
    'dict-remove': (['dict', 'any'], 'dict'),
    'dict-merge': (['dict', 'dict'], 'dict'),
    'dict-set': (['dict', 'any', 'any'], 'dict'),
    'dict-get': (['dict', 'any', 'any'], None),

    # Set operations
    'set?': (['any'], 'boolean'),
    'set=?': (['set', 'set'], 'boolean'),
    'set!=?': (['set', 'set'], 'boolean'),
    'set-member?': (['set', 'any'], 'boolean'),
    'set-add': (['set', 'any'], 'set'),
    'set-remove': (['set', 'any'], 'set'),
    'set-length': (['set'], 'integer'),
    'set-union': (['set', 'set'], 'set'),
    'set-intersection': (['set', 'set'], 'set'),
    'set-difference': (['set', 'set'], 'set'),
    'set-subset?': (['set', 'set'], 'boolean'),
    'set->list': (['set'], 'list'),

    # Struct operations
    'struct?': (['any'], 'boolean'),
    'struct-type?': (['struct-type', 'any'], 'boolean'),
    'struct-get': (['struct', 'any'], None),
    'struct-get-imm': (['struct', 'integer'], None),
    'struct-set': (['struct', 'any', 'any'], 'struct'),
    'struct-set-imm': (['struct', 'integer', 'any'], 'struct'),
    'struct=?': (['struct', 'struct'], 'boolean'),
    'struct!=?': (['struct', 'struct'], 'boolean'),
    'struct-type': (['struct'], None),
    'struct-type-name': (['struct-type'], 'string'),
    'struct-fields': (['struct-type'], 'list'),

    # Range
    'range': (['integer', 'integer', 'integer'], 'list'),

    # Bytes operations — type foundation
    'bytes?': (['any'], 'boolean'),
    'bytes=?': (['bytes', 'bytes'], 'boolean'),
    'bytes!=?': (['bytes', 'bytes'], 'boolean'),
    'bytes-length': (['bytes'], 'integer'),
    'bytes-ref': (['bytes', 'integer'], 'integer'),
    'bytes-append-u8': (['bytes', 'integer'], 'bytes'),
    'bytes-slice': (['bytes', 'integer', 'integer'], 'bytes'),
    'string->bytes': (['string'], 'bytes'),
    'bytes->string': (['bytes'], 'string'),
    'bytes->list': (['bytes'], 'list'),
    'bytes->string-hex': (['bytes'], 'string'),
    'string-hex->bytes': (['string'], 'bytes'),
    'bytes-concat': (['bytes', 'bytes'], 'bytes'),
    'bytes-index': (['bytes', 'bytes'], None),
    'bytes-index-int': (['bytes', 'integer'], 'integer'),
    'bytes<?': (['bytes', 'bytes'], 'boolean'),
    'bytes>?': (['bytes', 'bytes'], 'boolean'),
    'bytes<=?': (['bytes', 'bytes'], 'boolean'),
    'bytes>=?': (['bytes', 'bytes'], 'boolean'),
    'bytes-read-u8': (['bytes', 'integer'], 'integer'),
    'bytes-read-u16-le': (['bytes', 'integer'], 'integer'),
    'bytes-read-u24-le': (['bytes', 'integer'], 'integer'),
    'bytes-read-u32-le': (['bytes', 'integer'], 'integer'),
    'bytes-read-u64-le': (['bytes', 'integer'], 'integer'),
    'bytes-read-u16-be': (['bytes', 'integer'], 'integer'),
    'bytes-read-u24-be': (['bytes', 'integer'], 'integer'),
    'bytes-read-u32-be': (['bytes', 'integer'], 'integer'),
    'bytes-read-u64-be': (['bytes', 'integer'], 'integer'),
    'bytes-read-i8': (['bytes', 'integer'], 'integer'),
    'bytes-read-i16-le': (['bytes', 'integer'], 'integer'),
    'bytes-read-i24-le': (['bytes', 'integer'], 'integer'),
    'bytes-read-i32-le': (['bytes', 'integer'], 'integer'),
    'bytes-read-i64-le': (['bytes', 'integer'], 'integer'),
    'bytes-read-i16-be': (['bytes', 'integer'], 'integer'),
    'bytes-read-i24-be': (['bytes', 'integer'], 'integer'),
    'bytes-read-i32-be': (['bytes', 'integer'], 'integer'),
    'bytes-read-i64-be': (['bytes', 'integer'], 'integer'),
    'bytes-append-u16-le': (['bytes', 'integer'], 'bytes'),
    'bytes-append-u16-be': (['bytes', 'integer'], 'bytes'),
    'bytes-append-u24-le': (['bytes', 'integer'], 'bytes'),
    'bytes-append-u24-be': (['bytes', 'integer'], 'bytes'),
    'bytes-append-u32-le': (['bytes', 'integer'], 'bytes'),
    'bytes-append-u32-be': (['bytes', 'integer'], 'bytes'),
    'bytes-append-u64-le': (['bytes', 'integer'], 'bytes'),
    'bytes-append-u64-be': (['bytes', 'integer'], 'bytes'),
    'bytes-append-i8': (['bytes', 'integer'], 'bytes'),
    'bytes-append-i16-le': (['bytes', 'integer'], 'bytes'),
    'bytes-append-i16-be': (['bytes', 'integer'], 'bytes'),
    'bytes-append-i24-le': (['bytes', 'integer'], 'bytes'),
    'bytes-append-i24-be': (['bytes', 'integer'], 'bytes'),
    'bytes-append-i32-le': (['bytes', 'integer'], 'bytes'),
    'bytes-append-i32-be': (['bytes', 'integer'], 'bytes'),
    'bytes-append-i64-le': (['bytes', 'integer'], 'bytes'),
    'bytes-append-i64-be': (['bytes', 'integer'], 'bytes'),
    'bytes-write-u8': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-write-u16-le': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-write-u16-be': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-write-u24-le': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-write-u24-be': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-write-u32-le': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-write-u32-be': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-write-u64-le': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-write-u64-be': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-write-i8': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-write-i16-le': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-write-i16-be': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-write-i24-le': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-write-i24-be': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-write-i32-le': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-write-i32-be': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-write-i64-le': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-write-i64-be': (['bytes', 'integer', 'integer'], 'bytes'),
    'bytes-read-uleb128': (['bytes', 'integer'], 'integer'),
    'bytes-append-uleb128': (['bytes', 'integer'], 'bytes'),
    'bytes-read-sleb128': (['bytes', 'integer'], 'integer'),
    'bytes-append-sleb128': (['bytes', 'integer'], 'bytes'),
}
