"""
Generate C opcode #define header from the Python Opcode enum.

Reads src/menai/bytecode/menai_bytecode.py, extracts every Opcode member,
and writes the corresponding C #define block to src/menai/vm/menai_vm_opcodes.h.

Usage:
    python -m tools.gen_opcode_defs
"""

import re
import sys
from pathlib import Path


def main() -> None:
    """
    Read the Opcode enum from menai_bytecode.py and write C #defines to menai_vm_opcodes.h.
    """

    base = Path(__file__).resolve().parent.parent
    bytecode_path = base / "src" / "menai" / "bytecode" / "menai_bytecode.py"
    output_path = base / "src" / "menai" / "vm" / "menai_vm_opcodes.h"

    source = bytecode_path.read_text(encoding="utf-8")

    pattern = re.compile(r"^\s+([A-Z][A-Z0-9_]*)\s*=\s*_op\((\d+)", re.MULTILINE)
    matches = pattern.findall(source)

    if not matches:
        print("ERROR: No opcode definitions found", file=sys.stderr)
        sys.exit(1)

    lines = [
        "/*",
        " * Opcode values — generated from menai_bytecode.py Opcode enum.",
        " * Do not edit this file by hand; regenerate with:",
        " *   python -m tools.gen_opcode_defs",
        " */",
        "#ifndef MENAI_VM_OPCODES_H",
        "#define MENAI_VM_OPCODES_H",
        "",
    ]

    for name, value in matches:
        c_name = f"OP_{name}"
        lines.append(f"#define {c_name} {value}")

    max_val = int(matches[-1][1])
    lines.append("")
    lines.append(f"/* Highest opcode: {max_val} */")
    lines.append("")
    lines.append("#endif /* MENAI_VM_OPCODES_H */")
    lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {len(matches)} opcode defines in {output_path}")


if __name__ == "__main__":
    main()
