"""
Generate the CRC-32 slice-by-8 lookup tables as a C header.

The tables implement CRC-32/ISO-HDLC (the zlib/PNG/ZIP polynomial 0xEDB88320,
reflected).  They are emitted as `static const` data so the VM carries no
mutable state and needs no runtime initialisation (see ADR-0006).

Usage:
    python -m tools.gen_crc32_tables
"""

import sys
from pathlib import Path

_POLY = 0xEDB88320


def _build_tables() -> list[list[int]]:
    """
    Build the eight 256-entry slice-by-8 tables.

    The first table is the standard byte-at-a-time reflected table.  Each
    subsequent table is derived from the previous one so that the low byte of
    the running CRC can be folded into a single 32-bit value.
    """

    table0: list[int] = []
    for n in range(256):
        c = n
        for _ in range(8):
            c = (c >> 1) ^ _POLY if c & 1 else c >> 1

        table0.append(c)

    tables = [table0]
    for _ in range(7):
        prev = tables[-1]
        tables.append([(prev[i] >> 8) ^ table0[prev[i] & 0xFF] for i in range(256)])

    return tables


def main() -> None:
    """
    Write the generated CRC-32 table header.
    """

    base = Path(__file__).resolve().parent.parent
    output_path = base / "src" / "menai" / "vm" / "menai_vm_crc32_tables.h"

    tables = _build_tables()

    lines = [
        "/*",
        " * CRC-32 slice-by-8 lookup tables \u2014 generated from tools/gen_crc32_tables.py.",
        " * Do not edit this file by hand; regenerate with:",
        " *   python -m tools.gen_crc32_tables",
        " *",
        " * These implement CRC-32/ISO-HDLC (reflected polynomial 0xEDB88320), the",
        " * checksum used by zlib, PNG and ZIP.",
        " */",
        "#ifndef MENAI_VM_CRC32_TABLES_H",
        "#define MENAI_VM_CRC32_TABLES_H",
        "",
        "#include <stdint.h>",
        "",
    ]

    for index, table in enumerate(tables):
        lines.append(f"static const uint32_t crc32_table{index}[256] = {{")
        for start in range(0, 256, 8):
            row = ", ".join(f"0x{value:08x}" for value in table[start:start + 8])
            lines.append(f"    {row},")

        lines.append("};")
        lines.append("")

    lines.append("#endif /* MENAI_VM_CRC32_TABLES_H */")
    lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated CRC-32 slice-by-8 tables in {output_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
